changelog:
  categories:
    - title: 🏕 Featuresxxa1
      labels:
        - '*'
      exclude:
        labels:
          - dependenciesxxa1
    - title: 👒 Dependenciesxxa1
      labels:
        - dependenciesxxaa1
