on: [push]
name: Azure ARM
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # Checkout code
            - uses: actions/checkout@main

              # Log into Azure
            - uses: azure/login@v1
              with:
                  creds: ${{ secrets.test500 }}

              # Deploy Bicep file
            - name: deploy
              uses: azure/arm-deploy@v1
              with:
                  subscriptionId: 008d7684-8ac8-4244-a9c8-ddc5a8968562
                  resourceGroupName: Bicep
                  template: ./main.bicep
#                   parameters: storagePrefix=stg
                  failOnStdErr: false
