on: [push]
name: Azure ARM
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # Checkout code
            - uses: actions/checkout@main

              # Log into Azure
            - uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS2 }}

              # Deploy Bicep file
            - name: deploy
              uses: azure/arm-deploy@v1
              with:
                  subscriptionId: f90ac299-dc82-441d-b4c2-1cc548a04411
                  resourceGroupName: Bicep
                  template: ./main.bicep
                  parameters: storagePrefix=stg
                  failOnStdErr: false
